# Generated by Django 4.0.4 on 2022-05-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('place_rate', models.ManyToManyField(to='places.place')),
                ('user_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.user')),
            ],
        ),
    ]
