# Generated by Django 4.0.4 on 2022-05-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='no_name', max_length=16),
        ),
    ]
