# Generated by Django 4.0.4 on 2022-05-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='place_rate',
            new_name='placeHasRate',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='user_rate',
            new_name='user_fk',
        ),
    ]
